### PR TITLE
Create Visual Studio Code extension

### PR DESCRIPTION
**Pull request by leftstick**
implement vscode extension, see below:

partial

### CODE REVIEW

**Comment by cirelli94** [comment]
Sadly it doesn't compile to me using ./mvnw clean package on the root of the repository:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project spring-javaformat-checkstyle: Compilation failure: Compilation failure: 
[ERROR] /home/cirelli/Projects/open-mind/spring-javaformat/spring-javaformat/spring-javaformat-checkstyle/src/test/java/io/spring/javaformat/checkstyle/AssertionsAuditListener.java:[78,25] reference to assertThat is ambiguous
[ERROR]   both method <T>assertThat(T) in org.assertj.core.api.Assertions and method assertThat(java.lang.CharSequence) in org.assertj.core.api.Assertions match
[ERROR] /home/cirelli/Projects/open-mind/spring-javaformat/spring-javaformat/spring-javaformat-checkstyle/src/test/java/io/spring/javaformat/checkstyle/AssertionsAuditListener.java:[78,65] cannot find symbol
[ERROR]   symbol:   method contains(java.lang.String)
[ERROR]   location: class org.assertj.core.api.AbstractComparableAssert<capture#1 of ?,java.lang.StringBuilder>
[ERROR] /home/cirelli/Projects/open-mind/spring-javaformat/spring-javaformat/spring-javaformat-checkstyle/src/test/java/io/spring/javaformat/checkstyle/AssertionsAuditListener.java:[81,25] reference to assertThat is ambiguous
[ERROR]   both method <T>assertThat(T) in org.assertj.core.api.Assertions and method assertThat(java.lang.CharSequence) in org.assertj.core.api.Assertions match
[ERROR] /home/cirelli/Projects/open-mind/spring-javaformat/spring-javaformat/spring-javaformat-checkstyle/src/test/java/io/spring/javaformat/checkstyle/AssertionsAuditListener.java:[81,65] cannot find symbol
[ERROR]   symbol:   method doesNotContain(java.lang.String)
[ERROR]   location: class org.assertj.core.api.AbstractComparableAssert<capture#2 of ?,java.lang.StringBuilder>
```

**Comment by cirelli94** [comment]
Hi @snicoll, is there any plan to merge this?

**Comment by snicoll** [comment]
@cirelli94 I don't know. We're lacking time to review this one and make up our mind about it, sorry.

**Comment by lfvjimisola** [comment]
Any updates on this?

Can't seem to find a decentformatter/validator that integrates nicely with VS Code and Maven. Google Style Guide, Spring Java Format and others do not handle lambdas good enough. Palantir is an alternative but  spotless VS Code extension is based on gradle (we use maven).

**Comment by wilkinsona** [comment]
I'm afraid not. We do not use vscode so it's difficult to find the time to review the proposal.

> Spring Java Format and others do not handle lambdas good enough

This confuses me a little. If you don't like how Spring Java Format handles lambdas why are you interested in its integration with vscode?

**Comment by lfvjimisola** [comment]
Regarding the review, ok I understand.

Not trying to confuse you on purpose but I can see that :) We have to decide on something and VS Code integration is a deciding factor. It could also be that we could use Spring Java Format as a baseline for an lambda adaption.

**Comment by lfvjimisola** [comment]
@wilkinsona With the updates on https://github.com/spring-io/spring-javaformat/issues/124 spring-javaformat would fit our needs. Our team uses VS Code. Is there anything I/we can do to assist with this PR, e.g. test?

**Comment by lfvjimisola** [comment]
@leftstick Would it be possible for you to update this PR to match the latest on main? I would gladly test it afterwards if needed.

**Comment by philwebb** [comment]
I've rebased the PR onto the latest `main` and I'm reviewing it again to see if we can consider merging it. It's going to take me a few days.

**Comment by lfvjimisola** [comment]
@philwebb Thank you! Please let me know if I can assist in _anyway_.

**Comment by philwebb** [comment]
Thanks very much for the PR @leftstick. I've merged this into `main` with some modifications. The main change I've made is to switch from an HTTP application to one that uses stdin/stdout to format the code. I realize that this might end up being slower, but I think it's a simpler approach that we'll have an easier time maintaining.

We don't have a lot of vscode expertise in the team, so we're going to need to rely on the community quite a bit for this extension. If anyone watching the issue wants to kick the tires the SNAPSHOT release is available at https://repo.spring.io/ui/native/snapshot/io/spring/javaformat/spring-javaformat-vscode-extension/0.0.36-SNAPSHOT/

**Comment by lfvjimisola** [comment]
@leftstick @philwebb Thank you very much. I just installed the extension and so far, so good.
The rest of our team will install it during this week.

@leftstick How much work would it be to upload it to the VS Code Extension Market place ([here](https://marketplace.visualstudio.com/vscode))? And is that something that the Spring team would approve? It would make it a lot easier to adopt and also the risk of having a mismatch between versions (Maven and VS Code) is reduced greatly.

I spotted a small error with a link [here](https://github.com/spring-io/spring-javaformat#visual-studio-code), see [DocumentFormattingEditProvider](https://code.visualstudio.com/api/references/vscode-api#DocumentFormattingEditProvider).

**Comment by leftstick** [comment]
@lfvjimisola it is quick simple to publish the extension to [vscode market place](https://marketplace.visualstudio.com/vscode), you will refer to the guide [publish-extension](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

**Comment by philwebb** [comment]
> I spotted a small error with a link

Thanks! Fixed that one now.

**Comment by philwebb** [comment]
If we want to publish the extension I think we should do it as part of our CI release process. For now, I suggest we try the manual install approach to make sure the extension works as expected.

**Comment by lfvjimisola** [comment]
@philwebb Yes, I agree. My thought was not to set it up now but rather curious on how much work it would be. We'll make sure to try it properly manually before adding it to CI release process.

**Pull request closed without merging**
